// src/components/AnimatedHeading.vue
<template>
  <h1 :class="className">
    <span
      v-for="(line, li) in lines"
      :key="li"
      style="display: block"
    >
      <span
        v-for="(char, ci) in line.split('')"
        :key="ci"
        :style="{
          display: 'inline-block',
          opacity: visibleChars.has(`${li}-${ci}`) ? 1 : 0,
          transform: visibleChars.has(`${li}-${ci}`) ? 'translateX(0)' : 'translateX(-18px)',
          transition: 'opacity 500ms ease, transform 500ms ease',
          whiteSpace: 'pre',
        }"
      >{{ char === ' ' ? ' ' : char }}</span>
    </span>
  </h1>
</template>

<script setup>
import { ref, reactive, onMounted, onUnmounted } from 'vue'

const props = defineProps({
  text:         { type: String, required: true },
  class:        { type: String, default: '' },
  initialDelay: { type: Number, default: 200 },
  charDelay:    { type: Number, default: 30 },
})

const className = props.class
const lines = props.text.split('\n')
const visibleChars = reactive(new Set())
const timers = []

onMounted(() => {
  lines.forEach((line, li) => {
    const prevChars = lines.slice(0, li).reduce((acc, l) => acc + l.length, 0)
    line.split('').forEach((_, ci) => {
      const delay = props.initialDelay + (prevChars + ci) * props.charDelay
      const t = setTimeout(() => { visibleChars.add(`${li}-${ci}`) }, delay)
      timers.push(t)
    })
  })
})

onUnmounted(() => timers.forEach(clearTimeout))
</script>

// bridge-hero/src/components/AnimatedHeading.tsx
import { useEffect, useState } from 'react'

interface AnimatedHeadingProps {
  text: string
  className?: string
  initialDelay?: number
  charDelay?: number
}

export default function AnimatedHeading({
  text,
  className = '',
  initialDelay = 200,
  charDelay = 30,
}: AnimatedHeadingProps) {
  const [visibleChars, setVisibleChars] = useState<Set<string>>(new Set())

  const lines = text.split('\n')

  const charKeys: string[] = []
  lines.forEach((line, li) => {
    line.split('').forEach((_, ci) => {
      charKeys.push(`${li}-${ci}`)
    })
  })

  useEffect(() => {
    const timers: ReturnType<typeof setTimeout>[] = []

    lines.forEach((line, lineIndex) => {
      const prevLineChars = lines
        .slice(0, lineIndex)
        .reduce((acc, l) => acc + l.length, 0)

      line.split('').forEach((_, charIndex) => {
        const globalIndex = prevLineChars + charIndex
        const delay = initialDelay + globalIndex * charDelay
        const key = `${lineIndex}-${charIndex}`
        const t = setTimeout(() => {
          setVisibleChars(prev => new Set(prev).add(key))
        }, delay)
        timers.push(t)
      })
    })

    return () => timers.forEach(clearTimeout)
  }, [])

  return (
    <h1 className={className}>
      {lines.map((line, lineIndex) => (
        <span key={lineIndex} style={{ display: 'block' }}>
          {line.split('').map((char, charIndex) => {
            const key = `${lineIndex}-${charIndex}`
            const visible = visibleChars.has(key)
            return (
              <span
                key={charIndex}
                style={{
                  display: 'inline-block',
                  opacity: visible ? 1 : 0,
                  transform: visible ? 'translateX(0)' : 'translateX(-18px)',
                  transition: 'opacity 500ms ease, transform 500ms ease',
                  whiteSpace: 'pre',
                }}
              >
                {char === ' ' ? '\u00A0' : char}
              </span>
            )
          })}
        </span>
      ))}
    </h1>
  )
}
