// bridge-hero/src/components/FadeIn.tsx
import { useEffect, useState } from 'react'
import type { ReactNode } from 'react'

interface FadeInProps {
  children: ReactNode
  delay?: number
  duration?: number
  className?: string
}

export default function FadeIn({ children, delay = 0, duration = 1000, className = '' }: FadeInProps) {
  const [visible, setVisible] = useState(false)

  useEffect(() => {
    const timer = setTimeout(() => setVisible(true), delay)
    return () => clearTimeout(timer)
  }, [delay])

  return (
    <div
      className={`transition-opacity ${className}`}
      style={{
        opacity: visible ? 1 : 0,
        transitionDuration: `${duration}ms`,
      }}
    >
      {children}
    </div>
  )
}

// src/components/FadeIn.vue
<template>
  <div
    :class="className"
    :style="{
      opacity: visible ? 1 : 0,
      transition: `opacity ${duration}ms ease`,
    }"
  >
    <slot />
  </div>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue'

const props = defineProps({
  delay:    { type: Number, default: 0 },
  duration: { type: Number, default: 1000 },
  class:    { type: String, default: '' },
})

const visible = ref(false)
const className = props.class

let timer = null
onMounted(() => {
  timer = setTimeout(() => { visible.value = true }, props.delay)
})
onUnmounted(() => { if (timer) clearTimeout(timer) })
</script>
